### ISSUE TITLE
SignUp component form should only wrap the input boxes and sign in button

### ISSUE THREAD

**Issue by maxkant** [munitum/one-issue#5]
The SignUp component has the `<form>` tag wrapping the entire component. This makes any button click in the component submit the form, which isn't what we want. 

We need something like (without styles):
```
<div>
...
(other content)
...
  <form>
    <input className="inp mt32" type="email" />
    <input className="inp mt8" type="password"/>
  </form>
</div>
```

**Comment by pawsys** [comment]
@maxkant I committed the fix to my branch
